apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K8sControlPlane
metadata:
  name: nestedcontrolplane-sample
spec:
  etcd:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: NestedEtcd
    name: nestedetcd-sample
  apiserver:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K8sAPIServer
    name: nestedapiserver-sample
  controllerManager:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: K8sControllerManager
    name: nestedcontrollermanager-sample
