---
apiVersion: v1
kind: Service
metadata:
  name: pl-etcd-client
  labels:
    etcd_cluster: pl-etcd
spec:
  ports:
    - name: etcd-client
      port: 2379
  selector:
    etcd_cluster: pl-etcd
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: pl-etcd
  labels:
    etcd_cluster: pl-etcd
spec:
  clusterIP: None
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  publishNotReadyAddresses: true
  selector:
    etcd_cluster: pl-etcd
